### ISSUE TITLE
Error #Include

### ISSUE THREAD

**Issue by Knoficooki** [johnBuffer/ZombieV#3]
## import paths not working.
In "main.cpp" the include paths don't have any data to connect like ' #include "Turret.hpp"  '  but it should be ' #include "../include/Turret.hpp"  '. This problem is not only at the main.cpp there are 227 including errors.

**Comment by johnBuffer** [comment]
Are you familiar with c++ compilation? did you use cmake to generate the project to compile? The include paths are set here

**Comment by Knoficooki** [comment]
oh yea sry was just a bit to fast
